server:
  port: 8080
spring:
  thymeleaf:
    cache: false #Spring boot dev tools
  application:
    name: customer
  datasource:
    password: password
    url: jdbc:postgresql://localhost:5432/customer
    username: dotmonsscode
  jpa:
    hibernate:
      ddl-auto: update #Change to update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true
  #  zipkin:
  #    base-url: http://localhost:9411
  #  rabbitmq:
  #    addresses: localhost:5672
  profiles:
    active: default

  #actuator
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
  info:
    env:
      enabled: true

#The two queue types are kafka_queue or rabbit_queue. Any selected option works below
queue:
  queuetype: kafka_queue

customer:
  secretKey: dotmonstokenkeyvalue2348nr984rnf9lkjrkje9034923u4hfr8u3984ffd
  saltValue: $2a$10$abcdefghijklmnopqrstuv

#End points:
customeruri:
  kafkauri: http://KAFKASMS/api/v1/sendsmstokafka
  rabbituri: http://SMSRABBITMQ/api/v1/smspublisher
  frauduri: http://FRAUD/api/v1/fraud-check/


