spring:
  application:
    name: TwilloSms
server:
  port: 8444

twilio:
  account_sid: 1
  auth_token: 1
  from_number: 1


smsmq:
  queuename: sms_queue
  exchangename: sms_exchange
  routingkey: rabbit_key