spring:
  application:
    name: TwilloSms
server:
  port: 8444

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    fetch-registry: true
    register-with-eureka: true
    enabled: true

twilio:
  account_sid:
  auth_token:
  from_number: 18647743796


smsmq:
  queuename: sms_queue
  exchangename: sms_exchange
  routingkey: rabbit_key