spring:
  application:
    name: TwilloSms
server:
  port: 8444

twilio:
  account_sid: AC6c181a387b2569b47ee541375364aa50
  auth_token: f51ac3da7f50c9c5eb9cf84f0e569d39
  from_number: 18647743796


smsmq:
  queuename: sms_queue
  exchangename: sms_exchange
  routingkey: rabbit_key