spring:
  application:
    name: kafkasms
  kafka:
    bootstrap-servers: localhost:29092
server:
  port: 8498


kafkasms:
  topicbuilder: dotmonsservice
  groupid: dotmonskafka
  uri: http://TWILLOSMS/api/v1/smstwillo